### ISSUE TITLE
make app-cal  ERROR: Building app failed.

### ISSUE THREAD

**Issue by Istiakmorsalin** [calabash/ios-webview-test-app#35]
After running the `make app-cal ` command, getting this:
```
bin/make/app-cal.sh

######## Preparing #######

INFO: Prepared install directory Products/app-cal
INFO: Prepared archive directory

######## Building CalWebView-cal.app #######

xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
ERROR: Building app failed.
make: *** [app-cal] Error 72
```

why is this happening ?

**Comment by jmoody** [comment]
Xcode is not installed?  Or `xcodebuild` is not in the PATH?

**Comment by Istiakmorsalin** [comment]
Xcode is installed. also xcode command line tools is installed

**Comment by jmoody** [comment]
> xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

That error is saying that Xcode is not installed and Xcode command line tools are not in the path.

Is this a CI machine?

**Comment by Istiakmorsalin** [comment]
its not a CI machine, Its a dev machine. 
Despite xcode and its command line tool is installed, i have no idea why this error is showing.

**Comment by jmoody** [comment]
Show me the output of:

```
$ echo $PATH
$ which xcrun
$ xcode-select --print-path
$ xcrun -fn xcodebuild
```

**Comment by Istiakmorsalin** [comment]
command:`$ echo $PATH`
output:`/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/slbd/Library/Android/sdk/platform-tools:/Users/slbd/Library/Android/sdk/tools:/Users/slbd/.swiftenv/shims:/Users/slbd/.swiftenv/bin`

command: `which xcrun`
output: `/usr/bin/xcrun`

command: `xcode-select --print-path`
output: `/Applications/Xcode 8.2.app/Contents/Developer`

command: `xcrun -fn xcodebuild`
output: ```xcrun: error: unrecognized option: -fn
Usage: xcrun [options] <tool name> ... arguments ...
Find and execute the named command line tool from the active developer
directory.```

**Comment by jmoody** [comment]
```
/Applications/Xcode 8.2.app/Contents/Developer
```

That path has a space it in which makes me think you renamed the directory.  If so, you must reboot your machine.

> xcrun -fn xcodebuild

My bad, that ^ was a typo.

```
# Try:
$ xcrun -n -f xcodebuild
```

**Comment by Istiakmorsalin** [comment]
Command: xcrun -n -f xcodebuild
Output: /Applications/Xcode 8.2.app/Contents/Developer/usr/bin/xcodebuild

**Comment by Istiakmorsalin** [comment]
@jmoody any update please?

**Comment by jmoody** [comment]
> xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

This is not an error I can help you with.  Something is wrong with you developer environment.
